### PR TITLE
Added an implicit conversion operator for Reprompt to eliminate the n…

### PR DESCRIPTION
**Pull request by MattRuwe**
…eed to use the constructor.  i.e.

Reprompt prompt = "Are you sure?";

### CODE REVIEW

**Comment by stoiveyp** [comment]
If the PR is to remove the constructor from Reprompt - could you please add a second operator for the SSML constructor, and a small test to ensure it isn't broken in the future.

For my own curiosity - Reprompt is a relatively friendly constructor for speech types and the operator will hide the underlying object model, which is inconsistent with the rest of the library (outside of ResponseBuilder), is this object a particular paint point?

**Comment by MattRuwe** [comment]
I can an additional operator, but I don't want to break the spirit of your library.  It's hardly a big deal, but I thought it edge up the usability ever so slightly.  I agree that being consistent throughout the library is important, so let me know which way to go.  I can either abandon this PR, or I can go through the rest of the library to enable the use of implicit conversion operators throughout.  Let me know which way you would like to proceed.

**Comment by timheuer** [comment]
I'd love to see some before/after samples of what a developer might write as a result of this.  Given Steven's comment about hiding the underlying model, it'd be nice to see how you saw value in this particular instance.  But yes, I'd say consistency will rule here...not to have just one use case if we should do it...then it should be in other places as well.  Honestly I've never used implicit so I'm not sure what awesomeness I gain and what readability I may lose?

**Comment by MattRuwe** [comment]
I can add some a few more tests to demonstrate.  It's definitely a style thing.  Some people love them, others not so much.  Personally, I think it makes the library easier to use, but does hide some of the implementation details.  In my opinion, that's a good thing.  It's your library, so I guess you get to choose. ;)  I'll follow up this week with some additional details.  Thanks.

**Comment by stoiveyp** [comment]
In this case I almost didn't comment at all because I actually agree a string would make the ResponseBuilder `.Ask` calls a lot better for reprompt (I constantly forget when I write those calls) - but I think the value is in overloads on the ResponseBuilder method, not an operator. If you're creating the object in isolation the constructor is so small there's no value from an operator, and part of the library benefit is it helps you learn the request/response syntax so it's easier to read in Amazon's tools which are almost always raw JSON - reprompt is an object you see all the time.

In terms of "awesomeness", operators can definitely deliver - the two instances Alexa.NET has of implicit operators currently:

IntentSignature - Amazon give us the signature as a string, so I didn't really want to complicate the JSON conversion, but there was little benefit to the string without the ability to parse it out into an object model to expose the detail to the developer. Still unsure this was the right call compared to a .Parse method on the object.
https://github.com/timheuer/alexa-skills-dotnet/blob/master/Alexa.NET/Request/IntentSignature.cs

APLValue in Alexa.NET.APL - the APL library relies heavily on implicit conversion; every property in every object can be either a specific type or a data binding string, so with no union types in .NET constructing objects was painful. To make the library usable for all but the most simple example, I added implicit operators to handle my "value" object
https://github.com/stoiveyp/Alexa.NET.APL/blob/master/Alexa.NET.APL/APLValue_T.cs

I think it's unfair to just say it's a style preference, it's about the right tool for the job.

**Comment by MattRuwe** [comment]
I'm pretty new to the library and to Alexa skills in general, so I'm not attached to any ideas.  I am, however, willing to help out if you guys want me to.  Changing the ResponseBuilder class is a good alternative to using implicit operators.

**Comment by MattRuwe** [comment]
I created overloads in the ResponseBuilder class as discussed.  It seems like a lot of code that could be eliminated by two lines of implicit conversion operators.  Just say'n.

**Comment by MattRuwe** [comment]
Any additional thoughts on this?  Let me know which (if any) approach you want to take.  If you want to keep the code in the ResponseBuilder, I'll add some supporting unit tests.

**Comment by MattRuwe** [comment]
So I guess the non-response implies that you don't want these changes in the repo?  I'll remove the PR in a couple of days if I don't hear from you.

**Comment by timheuer** [comment]
Hi @MattRuwe -- have to be honest, I just haven't had time to really think holistically about this.  Just been busy at 'real job' :-) -- I'm all for improvements, just would want it to be improvements consistent across the entire library rather than just specific areas; meaning 'is there other places where the pattern should be implemented so it doesn't look like we just cherry picked' kind of approach.

**Comment by MattRuwe** [comment]
Totally understand and no pressure intended.  Consistency is important, but even more so when you're building a library for other developers to consume.  I'm happy to make non-breaking changes throughout the library to support easier object construction.  I just don't want to spend a bunch of time doing it only to find out that it's inconsistent with your vision.

The main thing I've identified as a bit painful is the need to instantiate a Reprompt object for every "Ask".  In my limited use, I haven't seen any other areas of the library that would benefit from a similar change.

At the end of the day, the library is amazing and makes writing Alexa skills in my favorite language a breeze!  Thank you for building it!  I want to help make it better, but since this isn't my library, I need some direction.

I see 3 options:
1) Leave everything the same and abandon the PR
2) Use an implicit conversion operator, which was what the original PR had in it
3) Modify the ResponseBuilder class to accept strings in addition to Reprompt, which is what my most recent changes add.

I'm happy to make any sweeping changes that you see are needed to keep the library consistent.

Thanks!

**Pull request closed without merging**
