### PR TITLE
Signature verification helper class

### LINKED ISSUE #34: Signature Validation
How do you do the signature validation?
I'm struggling with validation of the signature, see [StackOverflow](https://stackoverflow.com/questions/44892713/alexa-skill-signature-validation-failing) or [Amazon Alexa Forum](https://forums.developer.amazon.com/questions/77731/dotnet-core-10-c-signature-validation.html).

I also tried [X509Certificate2.GetRSAPublicKey()](https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.rsacertificateextensions.getrsapublickey(v=vs.110).aspx), but the decrypt and other [functions](https://msdn.microsoft.com/en-us/library/system.security.cryptography.rsa_methods(v=vs.110).aspx) are crashing dotnet.

I would like to write a pr, when it's finished, so other devs could use your framework even more easier.

### PR DESCRIPTION
**Pull request by stoiveyp**
Adding a RequestVerification class with a Verify helper method to allow those Skills using Web APIs rather than Lambdas to ensure that the request has been sent from Amazon.

This should help resolve #34

### CODE REVIEW

**Comment by ThomasPe** [comment]
that's what I've been looking for! Did you use it in an ASP.NET Core Web API? How do you go about integrating this?

**Comment by stoiveyp** [comment]
When you get the request, Amazon sign the request with two headers:

*    Signature
*    SignatureCertChainUrl

So if you run the RequestVerification.Verify method, with the values from these two headers as the first two parameters, and the body of the request as the last, it should return a boolean value telling you whether or not the signature is valid.

For more information on the steps Amazon ask you to take, read up on the [Amazon Documentation for hosting a skill](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/developing-an-alexa-skill-as-a-web-service#checking-the-signature-of-the-request)

And as ever, let me know if you run into any trouble and I'll try and help out.

**Comment by ThomasPe** [comment]
I actually got it working wrapping it as middleware for asp.net core. Would you mind if I include your code in a package and put it on nuget?

**Comment by stoiveyp** [comment]
From my point of view I'm just really happy the code definitely works, wasn't sure I'd tested enough! Might it be useful to use Alexa.Net as a NuGet reference in your own package, so we can share any updates or fixes?

Either way - as long it's helped you I'm a happy guy. Alexa.Net has an MIT licence in the root of the repo, so stick with that and we're all good 😄

**Comment by ThomasPe** [comment]
sounds good. I'm also planning to put both into a bootstrap project to get started quickly.
Currently awaiting certification to see if it does check everything Amazon needs.

**Comment by ThomasPe** [comment]
Here you go - I've created 2 packages, one for the validation and a middleware for ASP.NET Core 2.0. Not thoroughly testet yet, though ^^
https://github.com/ThomasPe/Alexa.NET.Security

**Pull request merged**
