### PR TITLE
Update RequestedPermission.cs

### PR DESCRIPTION
**Pull request by peterfoot**
I've noticed recently that my code for logging the accepted permissions broke and the constant values used for Scope are now different.
I'm not sure how long ago these values changed. I'm also not sure if the address constants also need updating because I don't use those.

### CODE REVIEW

**Comment by timheuer** [comment]
Thanks for the PR @peterfoot -- I'm looking for confirmation in the Alexa docs as samples are still referring to the existing scope items.  Can you post a sanitized request/response here showing that it is invalid?  Also, if this does indeed end up being a change needed the tests need to change.

**Comment by peterfoot** [comment]
Here is the request that I get following a permission change to grant both read and write permissions to my list skill

````json
{
    "version": "1.1",
    "context": {
        "System": {
            "application": {
                "applicationId": "amzn1.ask.skill.***"
            },
            "user": {
                "userId": "amzn1.ask.account.***",
                "accessToken": "***",
                "permissions": {
                    "consentToken": "***"
                }
            },
            "apiEndpoint": "https://api.eu.amazonalexa.com",
            "apiAccessToken": "***"
        }
    },
    "request": {
        "type": "AlexaSkillEvent.SkillPermissionAccepted",
        "requestId": "***",
        "timestamp": "2021-09-02T13:40:29Z",
        "eventCreationTime": "2021-09-02T13:40:29Z",
        "eventPublishingTime": "2021-09-02T13:40:29Z",
        "body": {
            "acceptedPermissions": [
                {
                    "scope": "alexa::household:lists:read"
                },
                {
                    "scope": "alexa::household:lists:write"
                }
            ]
        }
    }
}
```

**Comment by stevenpears-bjss** [comment]
Think this is what you're after @timheuer, although I agree that the docs are inconsistent right now as this wasn't the first or second reference I found regardless the permissions: 
https://developer.amazon.com/en-US/docs/alexa/smapi/steps-to-create-a-list-skill.html#use-list-and-skill-events-in-your-list-skill-to-make-your-skill-responsive

**Comment by peterfoot** [comment]
Also, I don't know if this helps, but I've noticed that the SkillPermissionAccepted request come through twice - once with version 1.0 and once 1.1 however the content is exactly the same. I'm not sure if this is an Alexa bug where the 1.0 version should have the previously documented constants and the 1.1 version has the ones discovered here...

**Comment by timheuer** [comment]
Yeah I saw the same pointer...it frustrates me the only place that exists is basically in a tutorial.  I have a friend on Alexa and have pinged them on the side to see if I can get better info...I may poke into the Slack as well -- I'm just hesitant to make a change without some clear documentation to point to.

@peterfoot it's clear in your response output what is being provided but that is also the Accept**ed** permissions and I think the intent for our API here was for an `AskForPermissionConsentCard` usage in the request...but my expectation from an API standpoint on Alexa end is they would be consistent...

I don't want to pull this in just yet...let me see if I can get more clarity, but your output is pretty dang clear :-)

**Comment by timheuer** [comment]
Just an update I'm having a developer forum discussion with someone in the Alexa ether...last they indicated whas the correct requested permission scope is how the library currently has it and points to their sample: https://github.com/alexa-samples/list-api-list-access-demo/blob/main/lambda/custom/index.js#L44

I've asked why another sample (that Steven linked to above) shows a different scope.  My _guess_ here is that there is a difference in **request** permissions and **response** permission scope information.  I'll update this thread on the response, but so far Alexa devs are saying that the scope as-is in the library already is correct for requesting permissions.

**Comment by timheuer** [comment]
Sorry for the delay...I had engaged Alexa Developer support on this and they confirmed that the correct format for requesting permissions (which was the primary use in this lib) is the current format `read::alexa:household:list` so we won't pull in this particular PR.  I let them know that that your response on SkillPermissionAccepted is showing a different format. They are indicating they need to update some docs.  But they have confirmed that the format we have here today is the correct one for requesting permissions (AskForConsentCard for example)

**Pull request closed without merging**
