### PR TITLE
Add VideoApp interface support

### PR DESCRIPTION
**Pull request by stoiveyp**
- Add support for the VideoApp.Launch directive, one of the new directives added for devices such as the Amazon Echo Show.
- Add tests for the VideoApp directive.
- Move CompareJson test method into a utility class as almost all the tests use it.

**Reference:**
[VideoApp Interface Reference](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/videoapp-interface-reference)

### CODE REVIEW

**Comment by ShadananaK** [comment]
How to use the above feature in our skill. 

Please provide any document or sample for using above  "VideoApp.Launch" in our skill.

Thank you.

**Comment by stoiveyp** [comment]
Hi @ShadananaK 

If your skill has the Video App option enabled, this is an example of how you can add a video launch directive to the skill response

```csharp
public SkillResponse VideoLaunchExample()
        {
            var basic = ResponseBuilder.Empty();

            //Either
            
            basic.Response.Directives.Add(new VideoAppDirective("https://source.to/sample.mp4"));

            //Or

            var video = new VideoItem("https://source.to/sample.mp4")
            {
                Metadata =
                {
                    Title = "Video Title",
                    Subtitle = "Video Sub-Title"
                }
            };

            basic.Response.Directives.Add(new VideoAppDirective{VideoItem = video});

            return basic;
        }
```

**Comment by ShadananaK** [comment]
Thanks stoiveyp.

I am using nodejs SDK. I cant use java code.

Please provide the nodejs sample for the above feature.

Regards,
Shadanana

**Comment by stoiveyp** [comment]
@ShadananaK Alexa.Net is a .NET library, please raise an issue with https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs for NodeJS

**Comment by ShadananaK** [comment]
Ok.

Thanks for the information.

**Comment by Scriptworks** [comment]
Hi,

First of all thank you very much for all your effort creating this wrapper.

I'm just dropping a quick comment that I am having issues when I use the code example above. If I use  the "or" option I get the following error

The remote endpoint could not be called, or the response it returned was invalid.

I also noticed that the json response is not spitting out the type "VideoApp.Launch".

Thank you

**Comment by stoiveyp** [comment]
Thanks @Scriptworks - I've updated my answer with the corrected metadata object

**Pull request merged**
