### PR TITLE
.Net 4.6 support

### LINKED ISSUE #53: .Net Framework 4.5 version
First, thank you very much for your efforts in implementing and maintaining this library.
It would be great if there also was a version for old school .Net Framework.

I found this can easily be achieved by replacing
`
    <TargetFramework>netstandard1.6</TargetFramework>
`
with
`
    <TargetFrameworks>netstandard1.6;net45</TargetFrameworks>
`
in `Alexa.NET.csproj`. Turns out both versions get built and packed in `.nupkg` without any additional changes.

In fact, I'll go and submit a PR for this.

### PR DESCRIPTION
**Pull request by a-stankevich**
Added support for .Net Framework 4.5.
Resolves #53

### CODE REVIEW

**Comment by timheuer** [comment]
Thanks. Taking a look at this. I am curious what environment you are running this in that requires it. Your own web api and not Lambda?

**Comment by a-stankevich** [comment]
@timheuer Yes, it's a big ASP.NET Web API system with multiple integrations. Alexa is supposed to be one of them

**Comment by a-stankevich** [comment]
hey @timheuer, is there anything I can help with to get this merged?
Thanks

**Comment by timheuer** [comment]
Right now it does not build @a-stankevich, so that needs to be fixed

**Comment by a-stankevich** [comment]
Oh, I see that build at appveynor is green: https://ci.appveyor.com/project/TimHeuer/alexa-skills-dotnet/build/1.0.58-hqcexiwp
Where can I see it failing?

**Comment by timheuer** [comment]
Try to compile it :-) -- it fails with System.Net.Http

**Comment by a-stankevich** [comment]
It compiles perfectly for me:

And nuget even produces a proper package with support of both versions:


I'm using VS 2017 (15.4.0)

**Comment by psantiago1969** [comment]
I receive the following error.  Also using VS 2017 15.4.0
Request\RequestVerification.cs(4,18,4,22): error CS0234: The type or namespace name 'Http' does not exist in the namespace 'System.Net' (are you missing an assembly reference?)

**Comment by timheuer** [comment]
Yeah I'm hitting same compile error as @psantiago1969 in both CLI and VS2017 (15.4.0)

**Comment by a-stankevich** [comment]
1. Changed .NETFramework version to 4.6, where certificate verification methods were added
2. Added reference to System.Net.Http assembly containing HttpClient. Used version 4.1.0, same as in .NETStandard 1.6

**Comment by psantiago1969** [comment]
Compiles for me now!

**Comment by a-stankevich** [comment]
@timheuer does it compile for you now? any other issues to fix?

**Comment by a-stankevich** [comment]
Hey @timheuer, hope you're doing well. Are there any barriers for getting this PR merged?

**Comment by timheuer** [comment]
Circling back on this @a-stankevich -- have you confirmed the library does NOT work with your environment?  It should.  As I was about to merge this, adding this small change makes this no longer a x-platform buildable project as it now relies on .NET Framework targeting pack, which is Windows only.  I'd prefer not to complicate the local build scenario of this package.

Can you help me understand why the compiled .NET Standard library doesn't work with your environment?  It should be supported, but if I'm missing the error you are getting then can you share?

See: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by adriangodong** [comment]
@a-stankevich Looking at .NET Standard matrix, `net46` should be compatible up to `netstandard1.3` (instead of the current 1.6). Have you tried compiling for 1.3 and see if this fixes your issue?

**Comment by a-stankevich** [comment]
@timheuer I tested this once again with .net 4.6 and it works much better. With .Net 4.5 I was getting error `Package is not compatible with net45`. Now once I upgraded to 4.6, it's gone. So it seems like this PR can be closed now.

**Comment by a-stankevich** [comment]
@adriangodong current version now works too. By default it pulls a ton of other packages as well, but adding `<RestoreProjectStyle>PackageReference</RestoreProjectStyle>` seems to resolve this. I will still watch for possible dependency conflicts in my solution, but for now I closed this. Thank you

**Pull request closed without merging**
