### PR TITLE
Allow custom GetCertificate method in RequestVerfication

### PR DESCRIPTION
**Pull request by stoiveyp**
Based on the feedback of #184 this change would allow the current method of verification, where it works. If it doesn't then it allows the following without having to fork/alter code:

```csharp
 public static Task<X509Certificate2> GetCertificate(Uri certificatePath)
    {
        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
        byte[] certificate = null;
        using (var web = new WebClient())
        {
            certificate = web.DownloadData(certificatePath);
        }
        var cert = new X509Certificate2(certificate);
        return Task.FromResult(cert);
    }
...
var valid = RequestVeritication.Verify(encodedSignature, certificatePath, body, GetCertificate);
```

### CODE REVIEW

**Comment by davemen** [comment]
I'm still running into the same issue. My code below:
` private static async Task<bool> ValidateRequest(HttpRequest request, ILogger log, SkillRequest skillRequest)
        {
            request.Headers.TryGetValue("SignatureCertChainUrl", out var signatureChainUrl);
            if (string.IsNullOrWhiteSpace(signatureChainUrl))
            {
                log.LogError("Validation failed. Empty SignatureCertChainUrl header");
                return false;
            }

            Uri certUrl;
            try
            {
                certUrl = new Uri(signatureChainUrl);
            }
            catch
            {
                log.LogError($"Validation failed. SignatureChainUrl not valid: {signatureChainUrl}");
                return false;
            }

            request.Headers.TryGetValue("Signature", out var signature);
            if (string.IsNullOrWhiteSpace(signature))
            {
                log.LogError("Validation failed - Empty Signature header");
                return false;
            }

            request.Body.Position = 0;
            var body = await request.ReadAsStringAsync();
            request.Body.Position = 0;

            if (string.IsNullOrWhiteSpace(body))
            {
                log.LogError("Validation failed - the JSON is empty");
                return false;
            }

            bool isTimestampValid = RequestVerification.RequestTimestampWithinTolerance(skillRequest);
            bool valid = await RequestVerification.Verify(signature, certUrl, body, GetCertificate);


            if (!valid || !isTimestampValid)
            {
                log.LogError("Validation failed - RequestVerification failed");
                return false;
            }
            else
            {
                return true;
            }
        }
        public static Task<X509Certificate2> GetCertificate(Uri certificatePath)
        {
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            byte[] certificate = null;
            using (var web = new WebClient())
            {
                certificate = web.DownloadData(certificatePath);
            }
            var cert = new X509Certificate2(certificate);
            return Task.FromResult(cert);
        }`

**Comment by stoiveyp** [comment]
@davemen which issue are you having? Do you have any details we could look at?

**Comment by davemen** [comment]
I'm getting this error: 

**The skill end-point is not accepting valid signed requests.
The skill end-point is not accepting valid signed requests. Please make sure that your signature URL validation is correct.
Documentation Help:
Verifying the signature certificate URL: Click here**

When I debug the validation process using NGROK, I notice that this code never sends the BadRequest which makes me wonder if either my code above is wrong or the earlier implementation is no longer working.

The code is posted here if you want to see it directly: https://github.com/davemen/DaveMusicAlexa/blob/master/DaveMusicAlexa/ElanMusic.cs

**Comment by davemen** [comment]
It seems like something has changed in Alexa testing. As this comes up in every Alexa skill I create with Alexa.net. Any ideas how to fix @stoiveyp?

**Comment by stoiveyp** [comment]
@davemen Nothing springs to mind looking at your code. If you're not getting a response though, that points me more to an exception being raised - maybe put a try catch around the initial call to validate request, and return a BadRequestResult if you get an exception?

I know we have others who rely on this for their skills to work correctly and have reached out before - so I'm hoping it's something specific we can track down 🤞

**Comment by davemen** [comment]
The try / catch didn’t help unfortunately. I created a new skill to see if the issue remains and it does. :(

On Oct 1, 2020, at 12:15 AM, Steven Pears <notifications@github.com<mailto:notifications@github.com>> wrote:



@davemen<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdavemen&data=02%7C01%7C%7Caab8abf0046646396ca508d865d9cf43%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637371333435844106&sdata=%2F%2F14x%2Bfd8T0LnXMiTnCZgy1XNBK0MCi%2BTU0hpxPwRrw%3D&reserved=0> Nothing springs to mind looking at your code. If you're not getting a response though, that points me more to an exception being raised - maybe put a try catch around the initial call to validate request, and return a BadRequestResult if you get an exception?

I know we have others who rely on this for their skills to work correctly and have reached out before - so I'm hoping it's something specific we can track down 🤞

**Comment by stoiveyp** [comment]
Sorry @davemen but we’re saying it doesn’t return a value or an exception? Are we sure it’s invoking the code?

**Comment by davemen** [comment]
I ran it via NGROK to set breakpoints on exceptions. None of the exceptions were hit.

The code is executing but this error persists.

You should be able to replicate this with a new Alexa.NET<http://Alexa.NET> app. I just created a hello world one that ran into the exact same issue.

On Oct 1, 2020, at 1:46 PM, Steven Pears <notifications@github.com<mailto:notifications@github.com>> wrote:



Sorry @davemen<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdavemen&data=02%7C01%7C%7Cdbc57aa1074d4650a7bd08d8664b13e7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637371819917862146&sdata=7or1qt4%2FQsC%2BkIn%2BtdhDuha1JCGk1HLH%2B3pBwKJSIgw%3D&reserved=0> but we’re saying it doesn’t return a value or an exception? Are we sure it’s invoking the code?

**Comment by stoiveyp** [comment]
Oh that’s great, if the code is executing then we can output the result of the verification method to confirm it’s definitely returning false?

Right now I’m just trying to confirm if the issue is the code or the function, we’ve had issues that were Azure specific before (can’t do this myself, 10pm here and a long day - so replying on my phone 👍)

**Comment by davemen** [comment]
@stoiveyp I wonder if this issue: https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/648 is causing the same challenge for C# Azure functions?

**Comment by stoiveyp** [comment]
@davemen I've just created the below function app in Azure from scratch (My azure portal was literally empty before I created this app, I only use Azure when people have issues with one of my packages).

I created a v3 function app with a linux setup using VS 2019 community and this worked immediately - you'll notice there's no custom cert download method, default worked without trouble.

Whatever issue you're having isn't Azure or the library out of the box - which unfortunately is going to make it difficult to trace.

```csharp
            public static class Function1
    {
        [FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            if (req.Method == "GET")
            {
                return new ObjectResult("Endpoint disabled");
            }

            var encodedSig = req.Headers["Signature"];
            var certPath = new Uri(req.Headers["SignatureCertChainUrl"], UriKind.Absolute);
            var body = string.Empty;
            using (StreamReader reader = new StreamReader(req.Body))
            {
                body = await reader.ReadToEndAsync();
            }

            if (!await RequestVerification.Verify(encodedSig, certPath, body))
            {
                return new BadRequestResult();
            }

            var request = JsonConvert.DeserializeObject<SkillRequest>(body);

            if (!RequestVerification.RequestTimestampWithinTolerance(request))
            {
                return new BadRequestResult();
            }

            var result = ResponseBuilder.Ask("did this work?", null);
            return new JsonResult(result);
        }
    }
```

**Comment by davemen** [comment]
I followed along and did the same thing you recommended.

VS 2019 community Edition. Linux setup with a v3 function app. I copied and pasted your code into the function, added the latest Alexa.NET<http://Alexa.NET> nuget package and published to Azure. I then configured the skill on the Alexa site.

This is the error:
[cid:40F9C69E-C602-4A3A-99E6-1C57B2700DE9@lan]

On Oct 5, 2020, at 4:50 AM, Steven Pears <notifications@github.com<mailto:notifications@github.com>> wrote:



@davemen<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdavemen&data=02%7C01%7C%7Caf1906d9f4244aa6f4ef08d86924ced9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637374954088035504&sdata=4cApIld4CCBBlSQHo0HHzTko%2BjW9xXfxYZp%2F4ErTMIc%3D&reserved=0> I've just created the below function app in Azure from scratch (My azure portal was literally empty before I created this app, I only use Azure when people have issues with one of my packages).

I created a v3 function app with a linux setup using VS 2019 community and this worked immediately - you'll notice there's no custom cert download method, default worked without trouble.

Whatever issue you're having isn't Azure or the library out of the box - which unfortunately is going to make it difficult to trace.

            public static class Function1
    {
        [FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            if (req.Method == "GET")
            {
                return new ObjectResult("Endpoint disabled");
            }

            var encodedSig = req.Headers["Signature"];
            var certPath = new Uri(req.Headers["SignatureCertChainUrl"], UriKind.Absolute);
            var body = string.Empty;
            using (StreamReader reader = new StreamReader(req.Body))
            {
                body = await reader.ReadToEndAsync();
            }

            if (!await RequestVerification.Verify(encodedSig, certPath, body))
            {
                return new BadRequestResult();
            }

            var request = JsonConvert.DeserializeObject<SkillRequest>(body);

            if (!RequestVerification.RequestTimestampWithinTolerance(request))
            {
                return new BadRequestResult();
            }

            var result = ResponseBuilder.Ask("did this work?", null);
            return new JsonResult(result);
        }
    }

**Comment by stoiveyp** [comment]
Afraid the error didn't attach with the rest of the message

**Comment by davemen** [comment]
PastedGraphic-1

**Comment by stoiveyp** [comment]
I'm afraid at this point - without exception information from your Azure function or the request headers that it's using - there's nothing more I can suggest.

That error points at an outstanding issue with certificate URL validation, but without knowing the request that failed inside your code I can't guess at what it could be.

I know the validation works - but possibly an exception because they're sending bogus information. Butif that were the case then the try/catch you put around the validation call should have caught it and you said it still didn't work, so without specifics there's nothing more I can suggest.

**Comment by davemen** [comment]
Did you post your solution on the Alexa website and run through the certification step? Can you post your screenshot?

I’m fairly confident that this is not unique to me.

-Dave

On Oct 5, 2020, at 1:01 PM, Steven Pears <notifications@github.com<mailto:notifications@github.com>> wrote:



I'm afraid at this point - without exception information from your Azure function or the request headers that it's using - there's nothing more I can suggest.

That error points at an outstanding issue with certificate URL validation, but without knowing the request that failed inside your code I can't guess at what it could be.

I know the validation works - but possibly an exception because they're sending bogus information. Butif that were the case then the try/catch you put around the validation call should have caught it and you said it still didn't work, so without specifics there's nothing more I can suggest.

**Comment by davemen** [comment]
In my screenshot, I was using a File/New project with just your code. So you should see the exact same error.

-Dave

On Oct 5, 2020, at 12:27 PM, Dave Mendlen <davemen@hotmail.com> wrote:

﻿ I followed along and did the same thing you recommended.

VS 2019 community Edition. Linux setup with a v3 function app. I copied and pasted your code into the function, added the latest Alexa.NET<http://Alexa.NET> nuget package and published to Azure. I then configured the skill on the Alexa site.

This is the error:
<PastedGraphic-1.tiff>


On Oct 5, 2020, at 4:50 AM, Steven Pears <notifications@github.com<mailto:notifications@github.com>> wrote:



@davemen<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdavemen&data=02%7C01%7C%7Caf1906d9f4244aa6f4ef08d86924ced9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637374954088035504&sdata=4cApIld4CCBBlSQHo0HHzTko%2BjW9xXfxYZp%2F4ErTMIc%3D&reserved=0> I've just created the below function app in Azure from scratch (My azure portal was literally empty before I created this app, I only use Azure when people have issues with one of my packages).

I created a v3 function app with a linux setup using VS 2019 community and this worked immediately - you'll notice there's no custom cert download method, default worked without trouble.

Whatever issue you're having isn't Azure or the library out of the box - which unfortunately is going to make it difficult to trace.

            public static class Function1
    {
        [FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            if (req.Method == "GET")
            {
                return new ObjectResult("Endpoint disabled");
            }

            var encodedSig = req.Headers["Signature"];
            var certPath = new Uri(req.Headers["SignatureCertChainUrl"], UriKind.Absolute);
            var body = string.Empty;
            using (StreamReader reader = new StreamReader(req.Body))
            {
                body = await reader.ReadToEndAsync();
            }

            if (!await RequestVerification.Verify(encodedSig, certPath, body))
            {
                return new BadRequestResult();
            }

            var request = JsonConvert.DeserializeObject<SkillRequest>(body);

            if (!RequestVerification.RequestTimestampWithinTolerance(request))
            {
                return new BadRequestResult();
            }

            var result = ResponseBuilder.Ask("did this work?", null);
            return new JsonResult(result);
        }
    }

**Comment by stoiveyp** [comment]
@davemen I'm afraid as this is my free time - and you're asking me to create an entirely certified skill in azure to confirm something you're experiencing - I have to stop. I need the requests your azure function is being sent, or someone else who's got the same problem. I know the code works when the information is valid, so I need the request headers to understand what kind of invalid requests are being made.

**Comment by davemen** [comment]
I’m confused.

You said you tested this with the code you sent earlier. Did you test it or not?

If you did, you would have received the same error I did. If you didn’t then I’m not sure why you sent the earlier code?

-Dave

On Oct 5, 2020, at 1:15 PM, Steven Pears <notifications@github.com> wrote:

﻿

@davemen<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdavemen&data=02%7C01%7C%7C1f00d4e3a5e14be26cc208d8696b6ac2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637375257349577483&sdata=aKWKKQnkKK8EDgdtbzjDFaapJmBMRJW0giV1PGI7scM%3D&reserved=0> I'm afraid as this is my free time - and you're asking me to create an entirely certified skill in azure to confirm something you're experiencing - I have to stop. I need the requests your azure function is being sent, or someone else who's got the same problem. I know the code works when the information is valid, so I need the request headers to understand what kind of invalid requests are being made.

**Comment by stoiveyp** [comment]
I've created https://github.com/timheuer/alexa-skills-dotnet/issues/215 to try and find someone else with the same issue and possibly more information, as this thread is on a merged PR and won't be seen by anyone visiting.

**Comment by davemen** [comment]
Thank you

-Dave

On Oct 5, 2020, at 1:19 PM, Steven Pears <notifications@github.com> wrote:

﻿

I've created #215<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftimheuer%2Falexa-skills-dotnet%2Fissues%2F215&data=02%7C01%7C%7Ce2bb629c477146f8476608d8696c0427%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637375259925081204&sdata=31dfDtW4bIIeJnn%2F1rWzTSoiQ%2Fv7jDMOCoRywK9LFpc%3D&reserved=0> to try and find someone else with the same issue and possibly more information, as this thread is on a merged PR and won't be seen by anyone visiting.

**Comment by timheuer** [comment]
@davemen how are you deploying to Azure?  Are you creating the function in-portal usinc CSX or in VS and publishing to Azure another means (either from VS directly or via CI/CD workflows)?

**Comment by davemen** [comment]
Hi Tim.

I’m publishing from VS through the Publish to Azure dialog- I’m doing it directly.

On Oct 5, 2020, at 1:55 PM, Tim Heuer <notifications@github.com<mailto:notifications@github.com>> wrote:



@davemen<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdavemen&data=02%7C01%7C%7Cbd37e9d19d604936671e08d8697101fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637375281361699138&sdata=RP20Tv63vXSrjR1xPYh6XXsxgEp9swtYTRRzTmt1nGc%3D&reserved=0> how are you deploying to Azure? Are you creating the function in-portal usinc CSX or in VS and publishing to Azure another means (either from VS directly or via CI/CD workflows)?

**Comment by timheuer** [comment]
@davemen ok, thanks...which is Zip deploy and may be related to the javascript SDK issue as well.  THe other question I want to clarify is if in the exception you are seeing if NGROK is still in play here or not?  You mentioned that earlier and I wanted to isolate NGROK out of the call chain.

**Comment by davemen** [comment]
Yes, Zip Deploy. Problem occurs with and without Ngrok.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by timheuer** [comment]
Ok, @davemen just tried the same code as @stoiveyp in Azure Function on Linux with Zip deploy.  It failed unless m endpoint was using this option:
image

**Comment by davemen** [comment]
Yep - that’s what I have as well.

On Oct 5, 2020, at 2:39 PM, Tim Heuer <notifications@github.com<mailto:notifications@github.com>> wrote:



Ok, @davemen<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdavemen&data=02%7C01%7C%7C861c8819d94a4481db9508d869772d58%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637375307862185394&sdata=Vo6QwP82nFRbxoUWho7SuMgPh5V5%2FBvjf33X4seKpG0%3D&reserved=0> just tried the same code as @stoiveyp<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstoiveyp&data=02%7C01%7C%7C861c8819d94a4481db9508d869772d58%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637375307862195381&sdata=xBrBdAstowAs3AxuNsPaJfPdWs8q2BKz5vbEt6fI6nY%3D&reserved=0> in Azure Function on Linux with Zip deploy. It failed unless m endpoint was using this option:
[image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F4821%2F95134871-70528d80-0718-11eb-879f-c99b1c259a49.png&data=02%7C01%7C%7C861c8819d94a4481db9508d869772d58%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637375307862205350&sdata=86a7as5J9BcUD8zZrq5%2BDdnJXJSqoDanxWwu5XF3uGQ%3D&reserved=0>

**Comment by stoiveyp** [comment]
Just thought - my testing was in app with a valid url to ensure the library wasn't broken and that zip deploy with Linux worked - but if they send garbage in the url header it'd cause a 500 before it went anywhere near our library.

Might be worth wrapping the new uri call used for the cert path in a try catch - in case it's a uri parsing error that's the problem.

**Pull request merged**
